services:
  api:
    build:
      context: .
      target: dev
    env_file:
      - path: .env
        required: false
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog
    command: go run ./cmd
    tty: true

  db:
    image: postgres:17.4
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  mailhog:
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
  go_mod_cache:
