services:
  api:
    image: scaf-gin-api-runtime
    build:
      context: .
      target: runtime
    init: true
    env_file:
      - .env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "/app/healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 5
    restart: always

  migrate:
    image: scaf-gin-api-runtime
    build:
      context: .
      target: runtime
    profiles:
      - tools
    init: true
    env_file:
      - .env
    command: /app/migrate up
    restart: "no"
